default: &default
  adapter: postgresql
  encoding: unicode 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: qiita_app_development

test:
  <<: *default
  database: qiita_app_test

production:
  <<: *default
  database: qiita_app_production
  username: qiita_app
  password: <%= ENV['QIITA_APP_DATABASE_PASSWORD'] %>
